# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_summary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'log_summary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_summary.proto\x12\nlogsummary\" \n\x10\x41\x63tivityCategory\x12\x0c\n\x04name\x18\x01 \x01(\t\"R\n\x08\x41\x63tivity\x12\r\n\x05title\x18\x01 \x01(\t\x12\x37\n\x11\x61\x63tivity_category\x18\x02 \x01(\x0b\x32\x1c.logsummary.ActivityCategory\"d\n\x12\x41\x63tivityOccurrence\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x14\n\x0cis_completed\x18\x02 \x01(\x08\x12&\n\x08\x61\x63tivity\x18\x03 \x01(\x0b\x32\x14.logsummary.Activity\":\n\nLogRequest\x12,\n\x04logs\x18\x01 \x03(\x0b\x32\x1e.logsummary.ActivityOccurrence\"\x1e\n\x0bLogResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2U\n\x11LogSummaryService\x12@\n\rSummarizeLogs\x12\x16.logsummary.LogRequest\x1a\x17.logsummary.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_summary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVITYCATEGORY']._serialized_start=33
  _globals['_ACTIVITYCATEGORY']._serialized_end=65
  _globals['_ACTIVITY']._serialized_start=67
  _globals['_ACTIVITY']._serialized_end=149
  _globals['_ACTIVITYOCCURRENCE']._serialized_start=151
  _globals['_ACTIVITYOCCURRENCE']._serialized_end=251
  _globals['_LOGREQUEST']._serialized_start=253
  _globals['_LOGREQUEST']._serialized_end=311
  _globals['_LOGRESPONSE']._serialized_start=313
  _globals['_LOGRESPONSE']._serialized_end=343
  _globals['_LOGSUMMARYSERVICE']._serialized_start=345
  _globals['_LOGSUMMARYSERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
