# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import log_summary_pb2 as log__summary__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in log_summary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogSummaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SummarizeLogs = channel.unary_unary(
                '/logsummary.LogSummaryService/SummarizeLogs',
                request_serializer=log__summary__pb2.LogRequest.SerializeToString,
                response_deserializer=log__summary__pb2.LogResponse.FromString,
                _registered_method=True)


class LogSummaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SummarizeLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogSummaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SummarizeLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeLogs,
                    request_deserializer=log__summary__pb2.LogRequest.FromString,
                    response_serializer=log__summary__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logsummary.LogSummaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logsummary.LogSummaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogSummaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SummarizeLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logsummary.LogSummaryService/SummarizeLogs',
            log__summary__pb2.LogRequest.SerializeToString,
            log__summary__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
